/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AntiBriberyRouteImport } from './routes/anti-bribery'
import { Route as CommoditiesRouteImport } from './routes/commodities'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EsgPolicyRouteImport } from './routes/esg-policy'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ValueChainRouteImport } from './routes/value-chain'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutAllianceRouteImport } from './routes/about.alliance'
import { Route as AboutLeadershipRouteImport } from './routes/about.leadership'
import { Route as ValueChainIndexRouteImport } from './routes/value-chain.index'
import { Route as ValueChainDownstreamRouteImport } from './routes/value-chain.downstream'
import { Route as ValueChainMidstreamRouteImport } from './routes/value-chain.midstream'
import { Route as ValueChainTechnologyRouteImport } from './routes/value-chain.technology'
import { Route as ValueChainUpstreamRouteImport } from './routes/value-chain.upstream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AntiBriberyRoute = AntiBriberyRouteImport.update({
  id: '/anti-bribery',
  path: '/anti-bribery',
  getParentRoute: () => rootRouteImport,
} as any)
const CommoditiesRoute = CommoditiesRouteImport.update({
  id: '/commodities',
  path: '/commodities',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgPolicyRoute = EsgPolicyRouteImport.update({
  id: '/esg-policy',
  path: '/esg-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ValueChainRoute = ValueChainRouteImport.update({
  id: '/value-chain',
  path: '/value-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAllianceRoute = AboutAllianceRouteImport.update({
  id: '/alliance',
  path: '/alliance',
  getParentRoute: () => AboutRoute,
} as any)
const AboutLeadershipRoute = AboutLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => AboutRoute,
} as any)
const ValueChainIndexRoute = ValueChainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ValueChainRoute,
} as any)
const ValueChainDownstreamRoute = ValueChainDownstreamRouteImport.update({
  id: '/downstream',
  path: '/downstream',
  getParentRoute: () => ValueChainRoute,
} as any)
const ValueChainMidstreamRoute = ValueChainMidstreamRouteImport.update({
  id: '/midstream',
  path: '/midstream',
  getParentRoute: () => ValueChainRoute,
} as any)
const ValueChainTechnologyRoute = ValueChainTechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => ValueChainRoute,
} as any)
const ValueChainUpstreamRoute = ValueChainUpstreamRouteImport.update({
  id: '/upstream',
  path: '/upstream',
  getParentRoute: () => ValueChainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/anti-bribery': typeof AntiBriberyRoute
  '/commodities': typeof CommoditiesRoute
  '/contact': typeof ContactRoute
  '/esg-policy': typeof EsgPolicyRoute
  '/investors': typeof InvestorsRoute
  '/privacy': typeof PrivacyRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/value-chain': typeof ValueChainRouteWithChildren
  '/about/alliance': typeof AboutAllianceRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/value-chain/downstream': typeof ValueChainDownstreamRoute
  '/value-chain/midstream': typeof ValueChainMidstreamRoute
  '/value-chain/technology': typeof ValueChainTechnologyRoute
  '/value-chain/upstream': typeof ValueChainUpstreamRoute
  '/about/': typeof AboutIndexRoute
  '/value-chain/': typeof ValueChainIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anti-bribery': typeof AntiBriberyRoute
  '/commodities': typeof CommoditiesRoute
  '/contact': typeof ContactRoute
  '/esg-policy': typeof EsgPolicyRoute
  '/investors': typeof InvestorsRoute
  '/privacy': typeof PrivacyRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/about/alliance': typeof AboutAllianceRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/value-chain/downstream': typeof ValueChainDownstreamRoute
  '/value-chain/midstream': typeof ValueChainMidstreamRoute
  '/value-chain/technology': typeof ValueChainTechnologyRoute
  '/value-chain/upstream': typeof ValueChainUpstreamRoute
  '/about': typeof AboutIndexRoute
  '/value-chain': typeof ValueChainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/anti-bribery': typeof AntiBriberyRoute
  '/commodities': typeof CommoditiesRoute
  '/contact': typeof ContactRoute
  '/esg-policy': typeof EsgPolicyRoute
  '/investors': typeof InvestorsRoute
  '/privacy': typeof PrivacyRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/value-chain': typeof ValueChainRouteWithChildren
  '/about/alliance': typeof AboutAllianceRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/value-chain/downstream': typeof ValueChainDownstreamRoute
  '/value-chain/midstream': typeof ValueChainMidstreamRoute
  '/value-chain/technology': typeof ValueChainTechnologyRoute
  '/value-chain/upstream': typeof ValueChainUpstreamRoute
  '/about/': typeof AboutIndexRoute
  '/value-chain/': typeof ValueChainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/anti-bribery'
    | '/commodities'
    | '/contact'
    | '/esg-policy'
    | '/investors'
    | '/privacy'
    | '/sustainability'
    | '/terms'
    | '/value-chain'
    | '/about/alliance'
    | '/about/leadership'
    | '/value-chain/downstream'
    | '/value-chain/midstream'
    | '/value-chain/technology'
    | '/value-chain/upstream'
    | '/about/'
    | '/value-chain/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anti-bribery'
    | '/commodities'
    | '/contact'
    | '/esg-policy'
    | '/investors'
    | '/privacy'
    | '/sustainability'
    | '/terms'
    | '/about/alliance'
    | '/about/leadership'
    | '/value-chain/downstream'
    | '/value-chain/midstream'
    | '/value-chain/technology'
    | '/value-chain/upstream'
    | '/about'
    | '/value-chain'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/anti-bribery'
    | '/commodities'
    | '/contact'
    | '/esg-policy'
    | '/investors'
    | '/privacy'
    | '/sustainability'
    | '/terms'
    | '/value-chain'
    | '/about/alliance'
    | '/about/leadership'
    | '/value-chain/downstream'
    | '/value-chain/midstream'
    | '/value-chain/technology'
    | '/value-chain/upstream'
    | '/about/'
    | '/value-chain/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AntiBriberyRoute: typeof AntiBriberyRoute
  CommoditiesRoute: typeof CommoditiesRoute
  ContactRoute: typeof ContactRoute
  EsgPolicyRoute: typeof EsgPolicyRoute
  InvestorsRoute: typeof InvestorsRoute
  PrivacyRoute: typeof PrivacyRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsRoute: typeof TermsRoute
  ValueChainRoute: typeof ValueChainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anti-bribery': {
      id: '/anti-bribery'
      path: '/anti-bribery'
      fullPath: '/anti-bribery'
      preLoaderRoute: typeof AntiBriberyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commodities': {
      id: '/commodities'
      path: '/commodities'
      fullPath: '/commodities'
      preLoaderRoute: typeof CommoditiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg-policy': {
      id: '/esg-policy'
      path: '/esg-policy'
      fullPath: '/esg-policy'
      preLoaderRoute: typeof EsgPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/value-chain': {
      id: '/value-chain'
      path: '/value-chain'
      fullPath: '/value-chain'
      preLoaderRoute: typeof ValueChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/alliance': {
      id: '/about/alliance'
      path: '/alliance'
      fullPath: '/about/alliance'
      preLoaderRoute: typeof AboutAllianceRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/leadership': {
      id: '/about/leadership'
      path: '/leadership'
      fullPath: '/about/leadership'
      preLoaderRoute: typeof AboutLeadershipRouteImport
      parentRoute: typeof AboutRoute
    }
    '/value-chain/': {
      id: '/value-chain/'
      path: '/'
      fullPath: '/value-chain/'
      preLoaderRoute: typeof ValueChainIndexRouteImport
      parentRoute: typeof ValueChainRoute
    }
    '/value-chain/downstream': {
      id: '/value-chain/downstream'
      path: '/downstream'
      fullPath: '/value-chain/downstream'
      preLoaderRoute: typeof ValueChainDownstreamRouteImport
      parentRoute: typeof ValueChainRoute
    }
    '/value-chain/midstream': {
      id: '/value-chain/midstream'
      path: '/midstream'
      fullPath: '/value-chain/midstream'
      preLoaderRoute: typeof ValueChainMidstreamRouteImport
      parentRoute: typeof ValueChainRoute
    }
    '/value-chain/technology': {
      id: '/value-chain/technology'
      path: '/technology'
      fullPath: '/value-chain/technology'
      preLoaderRoute: typeof ValueChainTechnologyRouteImport
      parentRoute: typeof ValueChainRoute
    }
    '/value-chain/upstream': {
      id: '/value-chain/upstream'
      path: '/upstream'
      fullPath: '/value-chain/upstream'
      preLoaderRoute: typeof ValueChainUpstreamRouteImport
      parentRoute: typeof ValueChainRoute
    }
  }
}

interface AboutRouteChildren {
  AboutAllianceRoute: typeof AboutAllianceRoute
  AboutLeadershipRoute: typeof AboutLeadershipRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutAllianceRoute: AboutAllianceRoute,
  AboutLeadershipRoute: AboutLeadershipRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface ValueChainRouteChildren {
  ValueChainDownstreamRoute: typeof ValueChainDownstreamRoute
  ValueChainMidstreamRoute: typeof ValueChainMidstreamRoute
  ValueChainTechnologyRoute: typeof ValueChainTechnologyRoute
  ValueChainUpstreamRoute: typeof ValueChainUpstreamRoute
  ValueChainIndexRoute: typeof ValueChainIndexRoute
}

const ValueChainRouteChildren: ValueChainRouteChildren = {
  ValueChainDownstreamRoute: ValueChainDownstreamRoute,
  ValueChainMidstreamRoute: ValueChainMidstreamRoute,
  ValueChainTechnologyRoute: ValueChainTechnologyRoute,
  ValueChainUpstreamRoute: ValueChainUpstreamRoute,
  ValueChainIndexRoute: ValueChainIndexRoute,
}

const ValueChainRouteWithChildren = ValueChainRoute._addFileChildren(
  ValueChainRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AntiBriberyRoute: AntiBriberyRoute,
  CommoditiesRoute: CommoditiesRoute,
  ContactRoute: ContactRoute,
  EsgPolicyRoute: EsgPolicyRoute,
  InvestorsRoute: InvestorsRoute,
  PrivacyRoute: PrivacyRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsRoute: TermsRoute,
  ValueChainRoute: ValueChainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
